2019-08-10 23:22:50,000 passlib.registry registered 'md5_crypt' handler: <class 'passlib.handlers.md5_crypt.md5_crypt'>
2019-08-10 23:22:50,005 p=13693 u=ansible |  PLAY [create stack] ****************************************************************************************************************************************************
2019-08-10 23:22:50,012 p=13693 u=ansible |  TASK [Gathering Facts] *************************************************************************************************************************************************
2019-08-10 23:22:50,012 p=13693 u=ansible |  Saturday 10 August 2019  23:22:50 +0530 (0:00:00.054)       0:00:00.054 ******* 
2019-08-10 23:22:50,751 p=13693 u=ansible |  ok: [localhost]
2019-08-10 23:22:50,767 p=13693 u=ansible |  TASK [Ansible start date] **********************************************************************************************************************************************
2019-08-10 23:22:50,768 p=13693 u=ansible |  Saturday 10 August 2019  23:22:50 +0530 (0:00:00.755)       0:00:00.810 ******* 
2019-08-10 23:22:50,831 p=13693 u=ansible |  ok: [localhost] => {
    "ansible_date_time.date": "2019-08-10"
}
2019-08-10 23:22:50,843 p=13693 u=ansible |  TASK [ISBC] ************************************************************************************************************************************************************
2019-08-10 23:22:50,884 p=13693 u=ansible |  Saturday 10 August 2019  23:22:50 +0530 (0:00:00.116)       0:00:00.927 ******* 
2019-08-10 23:22:51,492 p=13693 u=ansible |  An exception occurred during task execution. To see the full traceback, use -vvv. The error was: keystoneauth1.exceptions.auth_plugins.MissingRequiredOptions: Auth plugin requires parameters which were not given: auth_url
2019-08-10 23:22:51,493 p=13693 u=ansible |  fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1565459570.9-148684675433500/AnsiballZ_os_stack.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1565459570.9-148684675433500/AnsiballZ_os_stack.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1565459570.9-148684675433500/AnsiballZ_os_stack.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_os_stack_payload_3R62t4/__main__.py\", line 276, in <module>\n  File \"/tmp/ansible_os_stack_payload_3R62t4/__main__.py\", line 238, in main\n  File \"/tmp/ansible_os_stack_payload_3R62t4/ansible_os_stack_payload.zip/ansible/module_utils/openstack.py\", line 154, in openstack_cloud_from_module\n  File \"/usr/lib/python2.7/site-packages/openstack/__init__.py\", line 59, in connect\n    options=options, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/openstack/config/__init__.py\", line 36, in get_cloud_region\n    return config.get_one(options=parsed_options, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/openstack/config/loader.py\", line 1077, in get_one\n    auth_plugin = loader.load_from_options(**config['auth'])\n  File \"/usr/lib/python2.7/site-packages/keystoneauth1/loading/base.py\", line 162, in load_from_options\n    raise exceptions.MissingRequiredOptions(missing_required)\nkeystoneauth1.exceptions.auth_plugins.MissingRequiredOptions: Auth plugin requires parameters which were not given: auth_url\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2019-08-10 23:22:51,493 p=13693 u=ansible |  ...ignoring
2019-08-10 23:22:51,505 p=13693 u=ansible |  TASK [Wait until the active instance pings] ****************************************************************************************************************************
2019-08-10 23:22:51,505 p=13693 u=ansible |  Saturday 10 August 2019  23:22:51 +0530 (0:00:00.620)       0:00:01.547 ******* 
2019-08-10 23:22:53,077 p=13693 u=ansible |   [ERROR]: User interrupted execution

